### ISSUE TITLE
whiteboard-basic demo websocket connecting state bug

### ISSUE THREAD

**Issue by FrancoWaisfeld** [syncosaurus/syncosaurus#17]
In the whiteboard-basic demo its possible to attempt to add a shape before the websocket connection is established, causing an error "uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state."

**Comment by sklarfox** [comment]
Addressed in this [PR](https://github.com/syncosaurus/syncosaurus/pull/30)
