### ISSUE TITLE
Need to remove hard coding of notifications

### ISSUE THREAD

**Issue by sklarfox** [syncosaurus/syncosaurus#5]
https://github.com/syncosaurus/syncosaurus/blob/d66610fd6a160d2c8b94f6d76099964ad118b59d/frontend/src/utils/syncosaurus.js#L22

As I was poking around the client-side framework files, I realized there is still some old hard-coding for the notifications, where only the `count` key is notified.

@emargetis Will this fall under the `useSubscribe` overhaul we have planned? I'm not sure exactly where this sits in the data flow of the new delta updates, or where you would get the strings necessary to parameterize this value.

**Comment by emargetis** [comment]
Yes, this should get addressed in the `useSubscribe` overhaul. Will close this issue when the branch with `useSubscribe` is merged into main.

**Comment by sklarfox** [comment]
Awesome, thats what I figured! Thanks for fixing it.
